// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuWR6SKFn-20m1g5baz17aMwomnpKtSjQ',
    appId: '1:265311014425:android:6b41fa38588dd166536488',
    messagingSenderId: '265311014425',
    projectId: 'myflutter-new-to-do',
    storageBucket: 'myflutter-new-to-do.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aTZfHXJ7pv4_bilClQ_HL-gh8m3a73Q',
    appId: '1:265311014425:ios:fe9cc2edb55e232b536488',
    messagingSenderId: '265311014425',
    projectId: 'myflutter-new-to-do',
    storageBucket: 'myflutter-new-to-do.firebasestorage.app',
    iosBundleId: 'com.example.notesDay',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD6Bo3ERnjU5xTX62dIHZHL7IDA9l-bAQ',
    appId: '1:265311014425:web:9cf4ae1bc7809584536488',
    messagingSenderId: '265311014425',
    projectId: 'myflutter-new-to-do',
    authDomain: 'myflutter-new-to-do.firebaseapp.com',
    storageBucket: 'myflutter-new-to-do.firebasestorage.app',
  );

}